### ISSUE TITLE
Unlink howto?

### ISSUE THREAD

**Issue by KhoaSydney** [OrKoN/npm-link-shared#1]
Hi @OrKoN ,

How do unlink everything? 

cheers,

**Comment by OrKoN** [comment]
Hi @KhoaSydney,

You can use `npm unlink` to unlink what you need. E.g. in your target package

```
npm unlink linked-package
```

and in the `linked-package` to remove global link:

```
npm unlink
```

The task of unlinking everything is not automated in `npm-link-shared` because it's not often needed (imo).
