### ISSUE TITLE
Support for peerDependencies

### ISSUE THREAD

**Issue by mtfranchetto** [OrKoN/npm-link-shared#14]
First of all, congrats for this extremely useful tool!
However, to cover all of my company needs this tool should also look for peerDependencies since we are using them for sharing common libraries.
Will it makes sense to have something like --include-dev but --include-peer for peer dependencies?
If it makes sense I'll do pull request myself.

Cheers
Mattia

**Comment by OrKoN** [comment]
Hey @mtfranchetto sure, feel free to create a pull request. The idea looks good to me.
