### ISSUE TITLE
Module 'string' is missing

### ISSUE THREAD

**Issue by mdorda** [OrKoN/npm-link-shared#18]
I have installed `npm-link-shared@0.5.3` globally and when I try to run it in my project, it throws error it cannot find module `string` (here: https://github.com/OrKoN/npm-link-shared/blob/master/index.js#L7).

I checked your **package.json** and also **package-lock.json** and there is no `string` module dependency.

Version `0.5.0` works like a charm. I did not try `0.5.1` nor `0.5.2`.

**Comment by OrKoN** [comment]
You are right. It seems I broke it in the latest version. It should be fixed now.

**Comment by mdorda** [comment]
Works for me. Thank you!
