### ISSUE TITLE
ignored due to missing or erroneous package.json issue in windows

### ISSUE THREAD

**Issue by behnamazimi** [OrKoN/npm-link-shared#23]
When I want to link my package (`try-to-publish`) to my maın project (`backoffice-frontend`) face this error: 

> ignored due to missing or erroneous package.json

The full result is:

> Will be installing modules from `C:\Users\Behnam\Documents\Projects\try-to-publish/` to `C:\Users\Behnam\Documents\Projects\backoffice_frontend/`...
> `C:\Users\Behnam\Documents\Projects\try-to-publish/build` ignored due to missing or erroneous package.json
> `C:\Users\Behnam\Documents\Projects\try-to-publish/node_modules` ignored due to missing or erroneous package.json
> `C:\Users\Behnam\Documents\Projects\try-to-publish/src` ignored due to missing or erroneous package.json

This is the command that I execute:

`npm-link-shared C:\Users\Behnam\Documents\Projects\try-to-publish C:\Users\Behnam\Documents\Projects\backoffice-frontend`

**Comment by OrKoN** [comment]
First argument must a path to the folder containing all of your shared packages. You seem to target an individual package instead. Also, packages must contain a valid package.json

**Comment by behnamazimi** [comment]
@OrKoN , I could not realize what you want to say! Could you explain it with an example?

**Comment by OrKoN** [comment]
1. Move your module `try-to-publish` to `C:\Users\Behnam\Documents\Projects\shared-modules` so that the path to it becomes `C:\Users\Behnam\Documents\Projects\shared-modules\try-to-publish`.
2. Run the comment as following: `npm-link-shared C:\Users\Behnam\Documents\Projects\shared-modules C:\Users\Behnam\Documents\Projects\backoffice-frontend`

**Comment by Alfetta159** [comment]
Why doesn't npm-link-shared give any indication why the package.json file is erroneous.
