### ISSUE TITLE
namespaced packages

### ISSUE THREAD

**Issue by kojuka** [OrKoN/npm-link-shared#3]
Very excited to see this project.  I've had npm-linking problems for a while now and its really getting old.

I have a package that I publish to a private repo using NPM's private repos feature.  I typically include the package like this:

`npm install @mynamespace/packagename`

when I try to use this package this is what I get:
`npm-link-shared ~/node_modules . @mynamespace/packagename`
`/Users/XXX/node_modules/@mynamespace ignored due to missing or erroneous package.json`

I've verified that the package.json is in fact correct.

Looks like npm-link-shared doesn't quite parse the namespaced package correctly.

**Comment by OrKoN** [comment]
Yes, that's is probably not supported as private packages appeared after this module. Some kind of check needs to be introduced to see if the package starts with a scope.

**Comment by OrKoN** [comment]
But do you run `npm install @mynamespace/packagename` and get the error?

**Comment by kojuka** [comment]
whoops  - typo
What I meant is this.  When I try to use the package to link to the namespaced package I get the following:

`npm-link-shared ~/node_modules . @mynamespace/packagename`
`/Users/XXX/node_modules/@mynamespace ignored due to missing or erroneous package.json`

**Comment by OrKoN** [comment]
I see. I will try to fix it. Help me test the change then.

**Comment by OrKoN** [comment]
@webular Please try now `npm install npm-link-shared@0.3.0 -g`

**Comment by kojuka** [comment]
Perfect thx.
